export const AppConst = {
  name: process.env.NEXT_PUBLIC_APP_NAME || "Rokado",
  tagline: process.env.NEXT_PUBLIC_APP_TAGLINE || "Financial Core & Ledger Management",
  logo: "/next.svg",
  color: "#6366f1",
};

export enum StateEnum {
  ANDHRA_PRADESH = "Andhra Pradesh",
  ARUNACHAL_PRADESH = "Arunachal Pradesh",
  ASSAM = "Assam",
  BIHAR = "Bihar",
  CHHATTISGARH = "Chhattisgarh",
  GOA = "Goa",
  GUJARAT = "Gujarat",
  HARYANA = "Haryana",
  HIMACHAL_PRADESH = "Himachal Pradesh",
  JAMMU_KASHMIR = "Jammu and Kashmir",
  JHARKHAND = "Jharkhand",
  KARNATAKA = "Karnataka",
  KERALA = "Kerala",
  MADHYA_PRADESH = "Madhya Pradesh",
  MAHARASHTRA = "Maharashtra",
  MANIPUR = "Manipur",
  MEGHALAYA = "Meghalaya",
  MIZORAM = "Mizoram",
  NAGALAND = "Nagaland",
  ODISHA = "Odisha",
  PUNJAB = "Punjab",
  RAJASTHAN = "Rajasthan",
  SIKKIM = "Sikkim",
  TAMIL_NADU = "Tamil Nadu",
  TELANGANA = "Telangana",
  TRIPURA = "Tripura",
  UTTAR_PRADESH = "Uttar Pradesh",
  UTTARAKHAND = "Uttarakhand",
  WEST_BENGAL = "West Bengal",
  ANDAMAN_NICOBAR = "Andaman and Nicobar Islands",
  CHANDIGARH = "Chandigarh",
  DADRA_NAGAR_HAVELI_DAMAN_DIU = "Dadra and Nagar Haveli and Daman and Diu",
  DELHI = "Delhi",
  LAKSHADWEEP = "Lakshadweep",
  PUDUCHERRY = "Puducherry",
  LADAKH = "Ladakh"
}

export enum UnitEnum {
  PCS = "PCS (Pieces)",
  NOS = "NOS (Numbers)",
  MTR = "MTR (Meters)",
  KGS = "KGS (Kilograms)",
  GMS = "GMS (Grams)",
  LTR = "LTR (Liters)",
  ML = "ML (Milliliters)",
  BOX = "BOX (Boxes)",
  PKT = "PKT (Packets)",
  YRD = "YRD (Yards)",
  SQF = "SQF (Sq. Feet)",
  SQM = "SQM (Sq. Meters)",
  HRS = "HRS (Hours)",
  DAY = "DAY (Days)",
}

export enum CurrencyEnum {
  INR = "INR",
  USD = "USD",
  EUR = "EUR",
  GBP = "GBP",
  AED = "AED",
  AUD = "AUD",
  CAD = "CAD",
  CHF = "CHF",
  CNY = "CNY",
  DKK = "DKK",
  HKD = "HKD",
  JPY = "JPY",
  NOK = "NOK",
  NZD = "NZD",
  SEK = "SEK",
  SGD = "SGD",
  TRY = "TRY",
  ZAR = "ZAR",
}

export enum CurrencySymbolEnum {
  INR = "₹",
  USD = "$",
  EUR = "€",
  GBP = "£",
  AED = "د.إ",
  AUD = "$",
  CAD = "$",
  CHF = "Fr",
  CNY = "¥",
  DKK = "kr",
  HKD = "HK$",
  JPY = "¥",
  NOK = "kr",
  NZD = "$",
  SEK = "kr",
  SGD = "$",
  TRY = "₺",
  ZAR = "R",
}

// Generic GST rate brackets — applicable for any industry
export const GST_RATES = [0, 3, 5, 12, 18, 28];

export const GST_RATE_LABELS: Record<number, string> = {
  0: "0% — Exempt / Nil Rated",
  3: "3% — Special Rate",
  5: "5% — Low Rate",
  12: "12% — Standard Rate",
  18: "18% — Higher Rate",
  28: "28% — Premium / Luxury Rate",
};